package com.playchords.model

enum class ProgressionTag {
    CADENTIAL, LIFT, LOOP, OPEN, PIVOT, COLOR,

    IWANT_OPENING, IWANT_MAIN, IWANT_DESIRE, IWANT_CLIMAX,
    ILOVE_OPENING, ILOVE_MAIN_LOVE_THEME, ILOVE_VARIANT_LOVE_THEME, ILOVE_CLIMAX,
    COMEDY_CHORUS, COMEDY_VERSE, COMEDY_BRIDGE,
    SECTION_RESOLUTION,
}
